export const IPFS_FETCH = 'ipfs/IPFS_FETCH'
export const IPFS_FETCH_COMPLETED = 'ipfs/IPFS_FETCH_COMPLETED'
export const IPFS_FETCH_FAILED = 'ipfs/IPFS_FETCH_FAILED'

export const IPFS_SETUP = 'ipfs/IPFS_SETUP'
export const IPFS_SETUP_COMPLETED = 'ipfs/IPFS_SETUP_COMPLETED'
export const IPFS_SETUP_FAILED = 'ipfs/IPFS_SETUP_FAILED'

export const IPFS_UPDATE = 'ipfs/IPFS_UPDATE'
export const IPFS_UPDATE_COMPLETED = 'ipfs/IPFS_UPDATE_COMPLETED'
export const IPFS_UPDATE_FAILED = 'ipfs/IPFS_UPDATE_FAILED'

export const IPFS_GETADDRESS = 'ipfs/IPFS_GETADDRESS'
export const IPFS_GETADDRESS_COMPLETED = 'ipfs/IPFS_GETADDRESS_COMPLETED'
export const IPFS_GETADDRESS_FAILED = 'ipfs/IPFS_GETADDRESS_FAILED'
