export const USER_FETCH = 'agist/USER_FETCH'
export const USER_FETCH_COMPLETED = 'agist/USER_FETCH_COMPLETED'
export const USER_FETCH_FAILED = 'agist/USER_FETCH_FAILED'

export const USER_SETUP = 'agist/USER_SETUP'
export const USER_SETUP_COMPLETED = 'agist/USER_SETUP_COMPLETED'
export const USER_SETUP_FAILED = 'agist/USER_SETUP_FAILED'

export const USER_UPDATE = 'agist/USER_UPDATE'
export const USER_UPDATE_COMPLETED = 'agist/USER_UPDATE_COMPLETED'
export const USER_UPDATE_FAILED = 'agist/USER_UPDATE_FAILED'
